package com.csye6225.fall2018.courseservice3.Datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Announcements")
public class Announcements {
	
	private String Id;
	private String announcementId;
	private String announcementText;
	private String boardId;
	
	public Announcements() {
		
	}
	
	public Announcements(String Id,  String announcementId, String boardId, String announcementText) {
		this.Id=Id;
		this.announcementId=announcementId;
		this.boardId=boardId;
		this.announcementText = announcementText;
	}
	
	@DynamoDBHashKey(attributeName="Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return Id;
	}
	public void setId(String id) {
		Id = id;
	}
	
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "boardId-announcementId-index", attributeName = "boardId")
	public String getBoardId() {
		return boardId;
	}
	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}
	
	@DynamoDBIndexRangeKey(globalSecondaryIndexName = "boardId-announcementId-index", attributeName = "announcementId")
	public String getAnnouncementId() {
		return announcementId;
	}
	public void setAnnouncementId(String announcementId) {
		this.announcementId = announcementId;
	}
	
	@DynamoDBAttribute(attributeName = "announcementText")
	public String getAnnouncementText() {
		return announcementText;
	}
	public void setAnnouncementText(String announcementText) {
		this.announcementText = announcementText;
	}
	

}
	