package com.csye6225.fall2018.courseservice3.Datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Board")
public class Board {
	
	private String Id;
	private String courseId;
	private String boardId;
	
	public Board() {
		
	}
	
	public Board(String Id, String courseId, String boardId) {
		this.Id=Id;
		this.courseId=courseId;
		this.boardId=boardId;
	}
	
	@DynamoDBHashKey(attributeName="Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return Id;
	}
	public void setId(String id) {
		Id = id;
	}
	
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "boardId-index", attributeName = "boardId")
	public String getBoardId() {
		return boardId;
	}
	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}
	
	@DynamoDBAttribute(attributeName = "courseId")
	public String getCourseId() {
		return courseId;
	}
	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}	
}